name: UTS Website testing Workflow

on:
  push:
    branches:
      - main

jobs:
  run_workflow:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install selenium
    - name: Run Python script
      run: |
        python selenium-tutorial.ipynb
